"""API endpoint for food image analysis (CLIP + BLIP)."""
import io
import logging

from fastapi import APIRouter, File, HTTPException, UploadFile
from PIL import Image

from app.constants import ALLOWED_IMAGE_TYPES, MAX_IMAGE_SIZE_MB
from app.models.schemas import FoodImageAnalysisResponse
from app.services.food_image_service import FoodImageService

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/food-image", tags=["Food Image Analysis"])


def get_food_image_service() -> FoodImageService:
    from app.models.registry import get_food_image_analyzer
    return FoodImageService(analyzer=get_food_image_analyzer())


@router.post("/analyze", response_model=FoodImageAnalysisResponse)
async def analyze_food_image(file: UploadFile = File(...)):
    """
    Upload a food image and get:
    - **Dish name** identified by CLIP (zero-shot classification against 101 food classes)
    - **Visual description** generated by BLIP (image captioning)

    Accepts JPEG, PNG, or WebP images up to 10 MB.
    """
    if file.content_type not in ALLOWED_IMAGE_TYPES:
        raise HTTPException(
            status_code=400,
            detail=f"Invalid file type '{file.content_type}'. Allowed: JPEG, PNG, WebP",
        )

    contents = await file.read()
    size_mb = len(contents) / (1024 * 1024)
    if size_mb > MAX_IMAGE_SIZE_MB:
        raise HTTPException(
            status_code=400,
            detail=f"File too large ({size_mb:.1f} MB). Max: {MAX_IMAGE_SIZE_MB} MB",
        )

    try:
        image = Image.open(io.BytesIO(contents)).convert("RGB")
    except Exception:
        raise HTTPException(status_code=400, detail="Could not read image file")

    service = get_food_image_service()
    return service.analyze_image(image)
